/*
 * Copyright (C) 2016 - 2021 Marko Salmela
 *
 * http://fuusio.org
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
@file:Suppress("unused")

package org.fuusio.flx.core

const val NAME_ALPHA = "alpha"
const val NAME_ANONYMOUS = "<anonymous>"
const val NAME_ANY = "any"
const val NAME_ANYS = "any*"
const val NAME_ARGS = "args"
const val NAME_ARRAY = "array"
const val NAME_AUDIO_URI = "audioUri"
const val NAME_BASE = "base"
const val NAME_BINDINGS = "bindings"
const val NAME_BLUE = "blue"
const val NAME_BODY = "body"
const val NAME_CALLBACK = "callback"
const val NAME_CASE = "case"
const val NAME_CLASS = "class"
const val NAME_IS_CLASS = "is:class"
const val NAME_CLASS_NAME = "className"
const val NAME_CODE = "code"
const val NAME_CODE_BLOCK = "codeBlock"
const val NAME_COLLECTION = "collection"
const val NAME_COLLECTIONS = "collection*"
const val NAME_COLOR = "color"
const val NAME_CONDITION = "condition"
const val NAME_DATE = "date"
const val NAME_DIVIDER = "divider"
const val NAME_E = "e"
const val NAME_ELSE_FORM = "elseForm"
const val NAME_END = "end"
const val NAME_EXPRESSION = "expression"
const val NAME_EXPRESSIONS = "expression*"
const val NAME_FALLBACK = "fallback"
const val NAME_FALSE = "false"
const val NAME_FOO = "foo"
const val NAME_FORM = "form"
const val NAME_NOT_EQ_FORM = "!=:form"
const val NAME_GT_FORM = ">:form"
const val NAME_LT_FORM = "<:form"
const val NAME_EQ_FORM = "==:form"
const val NAME_GT_EQ_FORM = ">=:form"
const val NAME_LT_EQ_FORM = "<=:form"
const val NAME_DO_FORM = "do:form"
const val NAME_ELSE = "else"
const val NAME_FORM_1 = "form1"
const val NAME_FORM_2 = "form2"
const val NAME_FORMAT_ARGS = "formatArg*"
const val NAME_FORMS = "form*"
const val NAME_FUNCTION = "function"
const val NAME_FUNCTION_SYMBOL = "functionSymbol"
const val NAME_GREEN = "green"
const val NAME_IS_CASE_IGNORED = "isCaseIgnored"
const val NAME_INDEX = "index"
const val NAME_INDEXABLE = "indexable"
const val NAME_INFO = "info"
const val NAME_INITIAL_DELAY = "initialDelay"
const val NAME_INT = "int"
const val NAME_INTEGER = "integer"
const val NAME_INTERVAL = "interval"
const val NAME_INTS = "int*"
const val NAME_ITEM = "item"
const val NAME_JSON = "json"
const val NAME_JSON_PRIMITIVE = "jsonPrimitive"
const val NAME_KEY = "key"
const val NAME_LIMIT = "limit"
const val NAME_LIST = "list"
const val NAME_LITERAL = "literal"
const val NAME_LOCATION = "location"
const val NAME_MACRO = "macro"
const val NAME_MAP = "map"
const val NAME_MESSAGE = "message"
const val NAME_METHOD = "method"
const val MILLISECONDS = "milliseconds"
const val NAME_N = "n"
const val NAME_NAME = "name"
const val NAME_NAME_NAME = "name:name"
const val NAME_NEW_CHAR = "newChar"
const val NAME_NIL = "nil"
const val NAME_NULL = "null"
const val NAME_NUMBER = "number"
const val NAME_NUMBERS = "number*"
const val NAME_GT_NUMBERS = ">:number*"
const val NAME_GT_EQ_NUMBERS = ">=:number*"
const val NAME_LT_NUMBERS = "<:number*"
const val NAME_LT_EQ_NUMBERS = "<=:number*"
const val NAME_OLD_CHAR = "oldChar"
const val NAME_OBJECT = "object"
const val NAME_OBSERVABLE = "observable"
const val NAME_OBSERVER = "observer"
const val NAME_PARAMS = "param*"
const val NAME_PARAMETERS = "parameters"
const val NAME_PERIOD = "period"
const val NAME_PERCENTAGE = "percentage"
const val NAME_PI = "pi"
const val NAME_PLAYBACK = "playback"
const val NAME_POSTFIX = "postfix"
const val NAME_PREDICATE = "predicate"
const val NAME_PREFIX = "prefix"
const val NAME_PROPERTY= "property"
const val NAME_REGEX = "regex"
const val NAME_RED = "red"
const val NAME_REPLACEMENT = "replacement"
const val NAME_SCRIPT = "script"
const val NAME_SEQUENCE = "sequence"
const val NAME_SEQUENCES = "sequence*"
const val NAME_SET = "set"
const val NAME_IN_SEQUENCE = "in:sequence"
const val NAME_SIZEABLE = "sizeable"
const val NAME_SPACE = "space"
const val NAME_START = "start"
const val NAME_STRING = "string"
const val NAME_STRING_1 = "string1"
const val NAME_STRING_2 = "string2"
const val NAME_STRINGS = "string*"
const val NAME_SUBSTRING = "substring"
const val NAME_SUBSCRIPTION = "subscription"
const val NAME_SWITCH_VALUE = "switchValue"
const val NAME_SYMBOL = "symbol"
const val NAME_TRUE = "true"
const val NAME_THEN_FORM = "thenForm"
const val NAME_TOTAL = "total"
const val NAME_URL = "url"
const val NAME_VALUE = "value"
const val NAME_ASSIGN_VALUE = "=:value"
const val NAME_VALUES = "value*"
const val NAME_VALUE_OPTIONAL = "value?"
const val NAME_ASSIGN_VALUE_OPTIONAL = "=:value?"
const val NAME_VARIABLE = "variable"
const val NAME_VARIABLES = "variable*"
const val NAME_WHEN = "when"
const val NAME_X = "x"
const val NAME_Y = "y"